spring:
  application:
    name: Interview
  datasource:
    url: jdbc:mysql://localhost:3306/interview?serverTimezone=UTC
    username: root
    password: password1
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8080
interview:
  jwt:
    secret: cmVhbGx5Y29vbGFuZHNlY3VyZWRzZWNyZXRmb3Jqd3R0b2tlbgo
    expires: 3600000